---
- name: Populate service facts
  ansible.builtin.service_facts:

- name: Generate a certificate with an approle login
  hashicorp.vault.pki_certificate:
    role_name: shadowman-dev
    common_name: "{{ inventory_hostname }}"
    ttl: "{{ hashi_pki_certificate_ttl }}"
    url: "{{ hashi_url }}"
    auth_method: token
    token: "{{ hashi_token }}
    namespace: "root"
  delegate_to: localhost
  environment:
    REQUESTS_CA_BUNDLE: "{{ lookup('ansible.builtin.env', 'VAULT_CACERT') }}"
  register: cert_data
  when: ansible_facts['services']['httpd.service']['state'] | default('not-found') == "running"

- name: Deploy Cert
  ansible.builtin.copy:
    content: "{{ cert_data.data.certificate }}"
    dest: /etc/pki/tls/certs/localhost.crt
    owner: root
    group: root
    mode: "0644"
  notify: HTTPD_restart
  when: ansible_facts['services']['httpd.service']['state'] | default('not-found') == "running"

- name: Deploy Key
  ansible.builtin.copy:
    content: "{{ cert_data.data.private_key }}"
    dest: /etc/pki/tls/private/localhost.key
    owner: root
    group: root
    mode: "0400"
  notify: HTTPD_restart
  when: ansible_facts['services']['httpd.service']['state'] | default('not-found') == "running"
