---
- name: Gather current app releases
  ansible.builtin.uri:
    url: "https://cicd.shadowman.dev:3000/api/v1/repos/{{ gitea_user }}/{{ repo }}/releases"
    method: GET
    user: "{{ gitea_user }}"
    password: "{{ gitea_password }}"
    body_format: json
    force_basic_auth: true
    status_code: 200
    validate_certs: false
  register: releases

- name: Set Fact for next release version
  set_fact:
    tag: "{{ (releases.json[0].tag_name | default('0.9') | float + 0.1) | round(1,'common') }}"

- name: Create a Gitea Release using basic authentication
  ansible.builtin.uri:
    url: "https://cicd.shadowman.dev:3000/api/v1/repos/{{ gitea_user }}/{{ repo }}/releases"
    method: POST
    user: "{{ gitea_user }}"
    password: "{{ gitea_password }}"
    body_format: json
    force_basic_auth: true
    body:
      '{"target_commitish": "main",
      "name": "{{ repo }} {{ tag }}",
      "draft": false,
      "prerelease": false,
      "tag_name": "{{ tag }}"}'
    status_code: 201
    validate_certs: false
  register: __result
  until: __result.status == 201
  retries: 3
  delay: 3

- name: Save tag version for rest of workflow
  ansible.builtin.set_stats:
    data:
      release_tag: "{{ tag }}"