---
- name: RHEL website verification
  ansible.builtin.include_tasks: rhel_verification.yml
  when: os is match("rhel.*") or os == "Red Hat BYOL Linux"

- name: Windows website verification
  ansible.builtin.include_tasks: windows_verification.yml
  when: os is match("windows.*") or os is match("2016.*") or os == "Windows"
