---
- name: Start Httpd
  ansible.builtin.service:
    name: httpd
    state: started
  when: os is match("rhel.*") or os == "Red Hat BYOL Linux"

- name: Start IIS
  ansible.windows.win_service:
    name: W3Svc
    state: started
  when: os is match("windows.*") or os is match("2016.*") or os == "Windows"
