---
- name: Open Firewalld for apache
  ansible.posix.firewalld:
    service: http
    permanent: true
    state: enabled
  notify: Restart_firewalld

- name: Open Firewalld for SSL
  ansible.posix.firewalld:
    service: https
    permanent: true
    state: enabled
  notify: Restart_firewalld

- name: Add apache and SSL package for RHEL 7
  ansible.builtin.yum:
    name:
      - httpd
      - mod_ssl
    state: latest
  notify: HTTPD_running
  when: os is match("rhel.*7.*") or os is match ("rhel7.*")

- name: Add apache and SSL package for RHEL 8 or 9
  ansible.builtin.dnf:
    name:
      - httpd
      - mod_ssl
    state: latest
  notify: HTTPD_running
  when: os is match("rhel.*8.*") or os is match ("rhel8.*") or os is match("rhel.*9.*") or os is match ("rhel9.*")

- name: Copy website formatting
  ansible.builtin.copy:
    src: website/
    dest: /var/www/html/
    owner: root
    group: root
    mode: '0644'

- name: Copy Cert
  ansible.builtin.copy:
    src: /certs/shadowman_cert.cer
    dest: /etc/pki/tls/certs/localhost.crt
    owner: root
    group: root
    mode: '0644'

- name: Copy Key
  ansible.builtin.copy:
    src: /certs/shadowman_private.key
    dest: /etc/pki/tls/private/localhost.key
    owner: root
    group: root
    mode: '0644'

- name: Insert Index Page for webpage
  ansible.builtin.template:
    src: templates/indexcomplex.html.j2
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: '0644'
  tags:
    - updaterhel
