---
- name: Ensure Firewalld is installed
  ansible.builtin.package:
    name: firewalld
    state: present

- name: Open Firewalld for apache
  ansible.posix.firewalld:
    service: http
    permanent: true
    state: enabled
  notify: Restart_firewalld

- name: Open Firewalld for SSL
  ansible.posix.firewalld:
    service: https
    permanent: true
    state: enabled
  notify: Restart_firewalld

- name: Add apache and SSL package
  ansible.builtin.package:
    name:
      - httpd
      - mod_ssl
    state: present
  notify: HTTPD_running

- name: Copy website formatting
  ansible.posix.synchronize:
    src: website/
    dest: /var/www/html/
    owner: root
    group: root
    mode: "0644"
  tags:
    - updaterhel

- name: Copy Cert
  ansible.builtin.copy:
    src: /certs/shadowman_cert.cer
    dest: /etc/pki/tls/certs/localhost.crt
    owner: root
    group: root
    mode: "0644"

- name: Copy Key
  ansible.builtin.copy:
    src: /certs/shadowman_private.key
    dest: /etc/pki/tls/private/localhost.key
    owner: root
    group: root
    mode: "0400"

- name: Insert Index Page for webpage
  ansible.builtin.template:
    src: templates/indexcomplex.html.j2
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: "0644"
  tags:
    - updaterhel
